const data = {
  product: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shrit',
      categoty: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shrit',
      categoty: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReview: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Fit Pant',
      slug: 'nike-slim-pant',
      categoty: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReview: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'Adidas-fit-pant',
      categoty: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReview: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
